openapi: 3.0.0
servers:
  - url: /api/m1

info:
  version: 1.0.0
  title: Library Management System APIs

paths:
  /member-login:
    post:
      tags:
        - Member Authentication
      summary: Login member by email.
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: Member logged in successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /logout:
      post:
        tags:
          - User Authentication
        summary: Logout user and invalidate JWT token.
        description: ""
        responses:
          "200":
            description: Logged out successfully.
  '/books-history':
    get:
      security:
        - Bearer: []
      tags:
        - IssuedBook
      summary: get books history.
      description: ""
      parameters:
        - name: skip
          in: query
          description: skip record
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: limit record
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Books history retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IssuedBookResponse"
  '/search-books':
    get:
      security:
        - Bearer: []
      tags:
        - BookItems
      summary: book search.
      parameters:
        - name: id
          in: query
          description: book ids
          required: false
          schema:
            type: string
        - name: search_by_book
          in: query
          description: search by book true = 1/false =0
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: BookItem retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookItemResponse"

  '/member-details':
    get:
      security:
        - Bearer: []
      tags:
        - Members
      summary: get logged in member details.
      description: ""
      responses:
        "200":
          description: Member details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MemberResponse"
  "/update-member-profile":
    post:
      security:
        - Bearer: []
      tags:
        - Members
      summary: update logged in member profile.
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfile"
        required: true
      responses:
        "200":
          description: Member profile updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateMemberProfileResponse"

  "/register-member":
    post:
      security:
        - Bearer: []
      tags:
        - Members
      summary: registered new member.
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterProfile"
        required: true
      responses:
        "200":
          description: Registered successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterMemberProfileResponse"
  "/books/{id}/reserve-book":
    post:
      security:
        - Bearer: []
      tags:
        - IssuedBook
      summary: reserve book.
      description: ""
      parameters:
        - name: id
          in: path
          description: BookItem Id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Book reserved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReservedIssuedBookResponse"
  "/books/{id}/un-reserve-book":
    post:
      security:
        - Bearer: []
      tags:
        - IssuedBook
      summary: un-reserve book.
      description: ""
      parameters:
        - name: id
          in: path
          description: BookItem Id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Book un-reserved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReservedIssuedBookResponse"
  '/send-reset-member-password-link':
    post:
      security:
        - Bearer: []
      tags:
        - Members
      summary: send reset password link
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPassword"
        required: true
      responses:
        "200":
          description: Password reset link sent successfully.
  '/reset-member-password':
    post:
      security:
        - Bearer: []
      tags:
        - Members
      summary: reset password
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePassword"
        required: true
      responses:
        "200":
          description: Password updated successfully.

components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          properties:
            token:
              type: string
            user:
              $ref: "#/components/schemas/UserResponse"
    RegisterResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: "#/components/schemas/UserResponse"
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    RegisterUser:
      type: object
      required:
        - first_name
        - email
        - password
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        username:
          type: string
        password:
          type: string
        google2fa_secret:
          type: string

    BookResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: "#/components/schemas/UpdateUser"

    CreateUser:
      type: object
      required:
        - first_name
        - last_name
        - email
        - password
        - role_id
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        role_id:
          type: array
          items:
            type: integer
    UserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: "#/components/schemas/UpdateUser"
    UserListResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              first_name:
                type: string
              last_name:
                type: string
              email:
                type: string
              password:
                type: string
              role_id:
                type: array
                items:
                  type: integer
    UpdateUser:
      type: object
      required:
        - first_name
          - last_name
          - email
          - password
          - role_id
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        role_id:
          type: integer
    CreateMember:
      type: object
      required:
        - first_name
        - last_name
        - email
        - password
        - membership_plan_id
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        member_id:
          type: string
        password:
          type: string
        membership_plan_id:
          type: integer
    MemberResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: "#/components/schemas/UpdateMember"

    UpdateMember:
      type: object
      required:
        - first_name
        - last_name
        - email
        - password
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        email_verified_at:
            type: string
        phone:
          type: string
        image:
          type: string
        address:
          type: string
        image_path:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        is_default:
          type: integer
        is_active:
          type: boolean

    UpdateProfile:
        type: object
        required:
          - first_name
          - last_name
          - email
          - password
        properties:
          id:
            type: integer
          member_id:
            type: string
          first_name:
            type: string
          last_name:
            type: string
          email:
            type: string
          email_verified_at:
            type: string
          phone:
            type: string
          image:
            type: string
          address:
            type: string

    UpdateMemberProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: "#/components/schemas/UpdateProfile1"

    UpdateProfile1:
        type: object
        required:
          - first_name
          - last_name
          - email
          - password
        properties:
          id:
            type: integer
          member_id:
            type: string
          first_name:
            type: string
          last_name:
            type: string
          email:
            type: string
          email_verified_at:
            type: string
          phone:
            type: string
          image:
            type: string
          address:
            type: string
          image_path:
            type: string
          membership_plan_id:
            type: string
          activation_code:
            type: string
          created_at:
            type: string
          updated_at:
            type: string
          is_default:
            type: integer
          is_active:
            type: boolean

    RegisterProfile:
      type: object
      required:
        - first_name
        - last_name
        - email
        - password
      properties:
        id:
          type: integer
        member_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        email_verified_at:
          type: string
        phone:
          type: string
        image:
          type: string
        address:
          type: string

    RegisterMemberProfileResponse:
        type: object
        properties:
          success:
            type: boolean
          message:
            type: string
          data:
            $ref: "#/components/schemas/RegisterProfile1"

    RegisterProfile1:
        type: object
        required:
          - first_name
          - last_name
          - email
          - password
        properties:
          id:
            type: integer
          member_id:
            type: string
          first_name:
            type: string
          last_name:
            type: string
          email:
            type: string
          email_verified_at:
            type: string
          phone:
            type: string
          image:
            type: string
          address:
            type: string
          image_path:
            type: string
          membership_plan_id:
            type: string
          activation_code:
            type: string
          created_at:
            type: string
          updated_at:
            type: string
          is_default:
            type: integer
          is_active:
            type: boolean


    UpdateBookItem:
      type: object
      required:
        - id
      properties:
        book_id:
          type: integer
        book_code:
          type: string
        edition:
          type: string
        format:
          type: integer
        price:
          type: integer
        status:
          type: integer
        location:
          type: string
        language_id:
          type: integer
        publisher_id:
          type: integer
    AddItems:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              book_id:
                type: integer
              book_code:
                type: string
              edition:
                type: string
              format:
                type: integer
              price:
                type: integer
              status:
                type: integer
              location:
                type: string
              language_id:
                type: integer
              publisher_id:
                type: integer
    BookItemResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              language_name:
                type: integer
              authors:
                type: string
              status:
                type: integer

    ReserveBook:
      type: object
      required:
        - member_id
        - book_item_id
      properties:
        status:
          type: integer
    IssuedBookResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              code:
                type: integer
              image:
                type: string
              status:
                type: integer
    ReservedIssuedBookResponse:
        type: object
        properties:
          success:
            type: boolean
          message:
            type: string
          data:
              type: object
              properties:
                id:
                  type: integer
                status:
                  type: integer
                expected_available_date:
                  type: string
    CreateIssueBook:
      type: object
      properties:
        book_item_id:
          type: integer
        member_id:
          type: string
        status:
          type: integer
    UpdateIssueBook:
      properties:
        book_item_id:
          type: integer
        member_id:
          type: string
        status:
          type: integer
    ResetPassword:
      type: object
      required:
        - email
        - url
      properties:
        email:
          type: string
        url:
          type: string
    UpdatePassword:
      type: object
      required:
        - token
        - password
      properties:
        token:
          type: string
        password:
          type: string